name: PostgreSQL CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: miku
          POSTGRES_PASSWORD: b*rXfXYN*!7&LoPYHS^vj2bHmUE&&b%gGtWqpcmW2b24NpwxjRo$k!QB88KgnSdQ4%4PEsZU7KnNqH3LbnmpW&VtdYsEwuH66vehVvpyp&zjSB@ML7G&GWhVvWKZij!F
          POSTGRES_DB: MikuX_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        run: |
          psql -h localhost -U miku -c telegram_bot_schema.sql

      # Add other steps for building and testing your Telegram bot code
