name: PostgreSQL CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: miku
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to PostgreSQL
        run: psql -h localhost -U miku -d MikuX_db -c "SELECT version();"

      - name: Run SQL scripts
        run: |
          psql -h localhost -U miku -d miku_db -f telegram_bot_schema.sql
